[tox]
isolated_build = true
minversion = 3.22.0
envlist =
    pytest
    flake8
    format-check
    mypy

[testenv]
basepython = python3
deps =
    pytest: pytest-cov
    flake8: flake8 >= 7.0
    flake8: flake8-docstrings >= 1.7
    flake8: pep8-naming >= 0.13
    mypy: mypy >= 1.5
    mypy: types-requests
commands =
    pytest: pytest --verbose --cov=hassapi --cov-report=term-missing --cov-fail-under=80
    mypy: mypy --no-incremental src/hassapi
setenv =
    HASS_URL=X
    HASS_TOKEN=X

[testenv:flake8]
skip_install = true
commands =
    flake8 --max-line-length 99 src/hassapi setup.py

[testenv:format]
basepython = python3
description = format source code
deps = black >= 24.0
       isort[pyproject] >= 5.0
extras =
skip_install = true
commands =
    black src tests setup.py
    isort src tests setup.py

[testenv:format-check]
basepython = python3
description = check that the source code is well formatted
deps = {[testenv:format]deps}
skip_install = {[testenv:format]skip_install}
extras = {[testenv:format]extras}
commands =
    black --diff --check src tests setup.py
    isort --diff --check-only src tests setup.py

[isort]
multi_line_output = 3
include_trailing_comma = True
force_grid_wrap = 0
line_length = 99
known_first_party = hassapi
known_third_party = pytest,requests,setuptools

